import { DEVICE_TYPE_LABELS } from "@/lib/devices/devices";
import type { DeviceType } from "@/generated/prisma/enums";
import { cn } from "@/lib/utils";

/**
 * The sticker: QR on the left, asset tag and name on the right. Sized in
 * millimetres so it prints true on an A4 3×8 label sheet (70 × 37 mm).
 */
export function DeviceLabel({
  svg,
  assetTag,
  type,
  brand,
  model,
  className,
}: {
  svg: string;
  assetTag: string;
  type: DeviceType;
  brand: string;
  model: string;
  className?: string;
}) {
  return (
    <div
      className={cn(
        "flex h-[37mm] w-[70mm] items-center gap-[3mm] overflow-hidden bg-white p-[3mm] text-black",
        className,
      )}
    >
      <div
        className="size-[31mm] shrink-0 [&>svg]:size-full"
        // Generated by the qrcode library from our own URL, not user input.
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <div className="min-w-0 leading-tight">
        <p className="font-mono text-[11pt] font-semibold tracking-tight">{assetTag}</p>
        <p className="mt-[1mm] truncate text-[8pt]">
          {DEVICE_TYPE_LABELS[type]} · {brand}
        </p>
        <p className="truncate text-[8pt]">{model}</p>
        <p className="mt-[2mm] text-[6.5pt] text-zinc-600">Property of Madarth. Scan for details.</p>
      </div>
    </div>
  );
}
