import { DEVICE_TYPE_LABELS } from "@/lib/devices/devices";
import type { DeviceType } from "@/generated/prisma/enums";
import { cn } from "@/lib/utils";

/**
 * The sticker: QR on the left; on the right the asset tag (MAD-LAP-<emp
 * code> while assigned) and the holder's name, then the device. Sized in millimetres so it prints true on an A4 3×8 label sheet
 * (70 × 37 mm).
 */
export function DeviceLabel({
  svg,
  assetTag,
  type,
  brand,
  model,
  holder = null,
  stockTag = null,
  className,
}: {
  svg: string;
  assetTag: string;
  type: DeviceType;
  brand: string;
  model: string;
  holder?: { name: string } | null;
  /** The numbered tag, printed small when the asset tag is a holder's. */
  stockTag?: string | null;
  className?: string;
}) {
  const tag = assetTag;
  return (
    <div
      className={cn(
        "flex h-[37mm] w-[70mm] items-center gap-[3mm] overflow-hidden bg-white p-[3mm] text-black",
        className,
      )}
    >
      <div
        className="size-[29mm] shrink-0 [&>svg]:size-full"
        // Generated by the qrcode library from our own URL, not user input.
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      <div className="min-w-0 leading-tight">
        {/* One line always: employee-code tags run longer than asset tags. */}
        <p
          className={cn(
            "font-mono font-semibold tracking-tighter whitespace-nowrap",
            tag.length > 12 ? "text-[7.5pt]" : "text-[10pt]",
          )}
        >
          {tag}
        </p>
        {holder && <p className="mt-[0.5mm] truncate text-[9pt] font-semibold">{holder.name}</p>}
        <p className="mt-[1mm] truncate text-[7pt]">
          {DEVICE_TYPE_LABELS[type]} · {brand}
        </p>
        <p className="truncate text-[7pt]">{model}</p>
        <p className="mt-[1mm] text-[6pt] text-zinc-600">
          {stockTag && stockTag !== assetTag ? `${stockTag} · ` : ""}Property of Madarth
        </p>
      </div>
    </div>
  );
}
